=== IGSN/metadata/registration/1.1/igsn.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:igsn="http://schema.igsn.org/registration/1.1" targetNamespace="http://schema.igsn.org/registration/1.1" elementFormDefault="qualified">
  <xs:include schemaLocation="include/igsn-nameIdentifierScheme-v1.1.xsd"/>
  <xs:include schemaLocation="include/igsn-identifierType-v1.1.xsd"/>
  <xs:include schemaLocation="include/igsn-relatedIdentifierType-v1.1.xsd"/>
  <xs:include schemaLocation="include/igsn-relationType-v1.1.xsd"/>
  <xs:include schemaLocation="include/igsn-eventType-v1.1.xsd"/>
  <xs:include schemaLocation="include/igsn-dateType-v1.1.xsd"/>
  <xs:element name="sample">
    <xs:complexType>
      <xs:sequence>
        <!-- REQUIRED ELEMENTS -->
        <xs:element name="sampleNumber">
          <xs:complexType>
            <xs:simpleContent>
              <xs:extension base="xs:string">
                <xs:attribute name="identifierType" use="required" type="igsn:identifierType"/>
              </xs:extension>
            </xs:simpleContent>
          </xs:complexType>
        </xs:element>
        <xs:element name="registrant">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="registrantName" minOccurs="1">
                <xs:simpleType>
                  <xs:restriction base="xs:string"/>
                </xs:simpleType>
              </xs:element>
              <xs:element name="nameIdentifier" minOccurs="0">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute name="nameIdentifierScheme" use="required" type="igsn:nameIdentifier"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <!-- OPTIONAL ELEMENTS -->
        <xs:element name="relatedResourceIdentifiers" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="relatedResourceIdentifier" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute name="relatedIdentifierType" type="igsn:relatedIdentifierType"/>
                      <xs:attribute name="relationType" type="igsn:relationType"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <!-- ADMINISTRATIVE ELEMENTS -->
        <xs:element name="log" minOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="logElement" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute name="event" type="igsn:eventType" use="required"/>
                      <xs:attribute name="timeStamp" type="igsn:W3CDTFdate" use="required"/>
                      <xs:attribute name="comment" type="xs:string"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== IGSN/metadata/registration/1.1/igsn.xml
<sample xmlns="http://schema.igsn.org/registration/1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://schema.igsn.org/registration/1.1 http://schema.igsn.org/registration/1.1/igsn.xsd">

	<sampleNumber identifierType="igsn">20.500.11812/TESTIGSN</sampleNumber>

	<registrant>
		<registrantName>John Doe</registrantName>
 		<nameIdentifier nameIdentifierScheme="orcid">Test</nameIdentifier>
	</registrant>

	<relatedResourceIdentifiers>
		<relatedResourceIdentifier relatedIdentifierType="doi" relationType="IsCitedBy">10.5072/TEST</relatedResourceIdentifier>	
		<relatedResourceIdentifier relatedIdentifierType="handle" relationType="IsReferencedBy">10.5072/TEST2</relatedResourceIdentifier>
	</relatedResourceIdentifiers>

	<log>
	    <logElement event="registered" timeStamp="1997" comment="This is an optional comment"/>
	    <logElement event="submitted" timeStamp="1997-07"/>
	    <logElement event="updated" timeStamp="1997-07-16"/>
	    <logElement event="deprecated" timeStamp="1997-07-16T19:20:30.45+01:00"/>
   	    <logElement event="destroyed" timeStamp="1997-07-16T19:20+01:00"/>
	</log>

</sample>
